/**
 * 78장 타로 카드 이미지 매핑
 */

export const TAROT_IMAGE_MAP: Record<string, number> = {
  '0. 바보 카드.jpg': require('../assets/tarot/0. 바보 카드.jpg'),
  '1. 마법사 카드.jpg': require('../assets/tarot/1. 마법사 카드.jpg'),
  '2. 여사제 카드.jpg': require('../assets/tarot/2. 여사제 카드.jpg'),
  '3. 여황제 카드.jpg': require('../assets/tarot/3. 여황제 카드.jpg'),
  '4. 황제 카드.jpg': require('../assets/tarot/4. 황제 카드.jpg'),
  '5. 교황 카드.jpg': require('../assets/tarot/5. 교황 카드.jpg'),
  '6. 연인 카드.jpg': require('../assets/tarot/6. 연인 카드.jpg'),
  '7. 전차 카드.jpg': require('../assets/tarot/7. 전차 카드.jpg'),
  '8. 힘 카드.jpg': require('../assets/tarot/8. 힘 카드.jpg'),
  '9. 은둔자 카드.jpg': require('../assets/tarot/9. 은둔자 카드.jpg'),
  '10. 운명의 수레바퀴.jpg': require('../assets/tarot/10. 운명의 수레바퀴.jpg'),
  '11. 정의 카드.jpg': require('../assets/tarot/11. 정의 카드.jpg'),
  '12. 행맨 카드.jpg': require('../assets/tarot/12. 행맨 카드.jpg'),
  '13. 죽음 카드.jpg': require('../assets/tarot/13. 죽음 카드.jpg'),
  '14. 절제 카드.jpg': require('../assets/tarot/14. 절제 카드.jpg'),
  '15. 악마 카드.jpg': require('../assets/tarot/15. 악마 카드.jpg'),
  '16. 타워 카드.jpg': require('../assets/tarot/16. 타워 카드.jpg'),
  '17. 별 카드.jpg': require('../assets/tarot/17. 별 카드.jpg'),
  '18. 달 카드.jpg': require('../assets/tarot/18. 달 카드.jpg'),
  '19. 태양 카드.jpg': require('../assets/tarot/19. 태양 카드.jpg'),
  '20. 심판 카드.jpg': require('../assets/tarot/20. 심판 카드.jpg'),
  '21. 세계 카드.jpg': require('../assets/tarot/21. 세계 카드.jpg'),
  '완드 에이스.jpg': require('../assets/tarot/완드 에이스.jpg'),
  '완드2.jpg': require('../assets/tarot/완드2.jpg'),
  '완드3.jpg': require('../assets/tarot/완드3.jpg'),
  '완드4.jpg': require('../assets/tarot/완드4.jpg'),
  '완드5.jpg': require('../assets/tarot/완드5.jpg'),
  '완드6.jpg': require('../assets/tarot/완드6.jpg'),
  '완드7.jpg': require('../assets/tarot/완드7.jpg'),
  '완드8.jpg': require('../assets/tarot/완드8.jpg'),
  '완드9.jpg': require('../assets/tarot/완드9.jpg'),
  '완드10.jpg': require('../assets/tarot/완드10.jpg'),
  '완드 페이지.jpg': require('../assets/tarot/완드 페이지.jpg'),
  '완드 나이트.jpg': require('../assets/tarot/완드 나이트.jpg'),
  '완드 퀸.jpg': require('../assets/tarot/완드 퀸.jpg'),
  '완드 킹.jpg': require('../assets/tarot/완드 킹.jpg'),
  '컵 에이스.jpg': require('../assets/tarot/컵 에이스.jpg'),
  '컵2.jpg': require('../assets/tarot/컵2.jpg'),
  '컵3.jpg': require('../assets/tarot/컵3.jpg'),
  '컵4.jpg': require('../assets/tarot/컵4.jpg'),
  '컵5.jpg': require('../assets/tarot/컵5.jpg'),
  '컵6.jpg': require('../assets/tarot/컵6.jpg'),
  '컵7.jpg': require('../assets/tarot/컵7.jpg'),
  '컵8.jpg': require('../assets/tarot/컵8.jpg'),
  '컵9.jpg': require('../assets/tarot/컵9.jpg'),
  '컵10.jpg': require('../assets/tarot/컵10.jpg'),
  '컵 페이지.jpg': require('../assets/tarot/컵 페이지.jpg'),
  '컵 나이트.jpg': require('../assets/tarot/컵 나이트.jpg'),
  '컵 퀸.jpg': require('../assets/tarot/컵 퀸.jpg'),
  '컵 킹.jpg': require('../assets/tarot/컵 킹.jpg'),
  '소드 에이스.jpg': require('../assets/tarot/소드 에이스.jpg'),
  '소드2.jpg': require('../assets/tarot/소드2.jpg'),
  '소드3.jpg': require('../assets/tarot/소드3.jpg'),
  '소드4.jpg': require('../assets/tarot/소드4.jpg'),
  '소드5.jpg': require('../assets/tarot/소드5.jpg'),
  '소드6.jpg': require('../assets/tarot/소드6.jpg'),
  '소드7.jpg': require('../assets/tarot/소드7.jpg'),
  '소드8.jpg': require('../assets/tarot/소드8.jpg'),
  '소드9.jpg': require('../assets/tarot/소드9.jpg'),
  '소드10.jpg': require('../assets/tarot/소드10.jpg'),
  '소드 페이지.jpg': require('../assets/tarot/소드 페이지.jpg'),
  '소드 나이트.jpg': require('../assets/tarot/소드 나이트.jpg'),
  '소드 퀸.jpg': require('../assets/tarot/소드 퀸.jpg'),
  '소드 킹.jpg': require('../assets/tarot/소드 킹.jpg'),
  '펜타클 에이스.jpg': require('../assets/tarot/펜타클 에이스.jpg'),
  '펜타클2.jpg': require('../assets/tarot/펜타클2.jpg'),
  '펜타클3.jpg': require('../assets/tarot/펜타클3.jpg'),
  '펜타클4.jpg': require('../assets/tarot/펜타클4.jpg'),
  '펜타클5.jpg': require('../assets/tarot/펜타클5.jpg'),
  '펜타클6.jpg': require('../assets/tarot/펜타클6.jpg'),
  '펜타클7.jpg': require('../assets/tarot/펜타클7.jpg'),
  '펜타클8.jpg': require('../assets/tarot/펜타클8.jpg'),
  '펜타클9.jpg': require('../assets/tarot/펜타클9.jpg'),
  '펜타클10.jpg': require('../assets/tarot/펜타클10.jpg'),
  '펜타클 페이지.jpg': require('../assets/tarot/펜타클 페이지.jpg'),
  '펜타클 나이트.jpg': require('../assets/tarot/펜타클 나이트.jpg'),
  '펜타클 퀸.jpg': require('../assets/tarot/펜타클 퀸.jpg'),
  '펜타클 킹.jpg': require('../assets/tarot/펜타클 킹.jpg'),
};

export const CARD_BACK = require('../assets/tarot/카드뒷면.png');
